# Generated by Django 3.1 on 2021-03-08 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articul', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articul',
            options={'verbose_name': 'Артикул', 'verbose_name_plural': 'Артикулы'},
        ),
        migrations.RemoveField(
            model_name='articul',
            name='art',
        ),
        migrations.AddField(
            model_name='articul',
            name='artikuls',
            field=models.CharField(blank=True, max_length=64, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='articul',
            name='kod_phone',
            field=models.CharField(default=86191, help_text='Код стационарногономера телефона населенного пункта, 5 цифр.', max_length=5, verbose_name='Телефонный код'),
        ),
        migrations.AddField(
            model_name='articul',
            name='nomer',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='articul',
            name='status',
            field=models.CharField(default='000', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='articul',
            name='userartikul',
            field=models.ForeignKey(help_text='Укажите владельца артикула', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
