# Generated by Django 3.1 on 2021-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articul', '0003_auto_20210309_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='articul',
            name='data_vidan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
