# Generated by Django 3.1 on 2021-03-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articul', '0006_auto_20210311_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articul',
            name='tags',
        ),
    ]
