# Generated by Django 3.1 on 2021-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_zadacha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zadacha',
            options={'ordering': ['-data_postanovki'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateTimeField(default='2021-03-12', verbose_name='Дата задачи'),
        ),
    ]
