# Generated by Django 3.1 on 2021-03-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210312_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zadacha',
        ),
    ]
