# Generated by Django 3.1 on 2021-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadacha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadanie', models.CharField(default='Название', max_length=128, verbose_name='Задача')),
                ('data_postanovki', models.DateTimeField(default='2021-03-12', verbose_name='Дата задачи')),
                ('is_activ', models.BooleanField(default=True, verbose_name='В работе')),
                ('is_vipolneno', models.BooleanField(default=True, verbose_name='Задача выполнена')),
                ('data_vipolnenija', models.DateTimeField(verbose_name='Дата выполнения задачи')),
                ('descript', models.TextField(default='Указать задание', max_length=512, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-data_postanovki'],
            },
        ),
    ]
