# Generated by Django 3.1 on 2021-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0002_auto_20210312_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateField(default='12.03.2021', verbose_name='Дата задачи'),
        ),
    ]
