# Generated by Django 3.1 on 2021-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0003_auto_20210312_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateField(auto_now=True, verbose_name='Дата задачи'),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateField(verbose_name='Дата выполнения задачи'),
        ),
    ]
