# Generated by Django 3.1 on 2021-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0004_auto_20210312_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateTimeField(default='2021-03-12', verbose_name='Дата задачи'),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(verbose_name='Дата выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='is_vipolneno',
            field=models.BooleanField(default=True, verbose_name='Задача выполнена'),
        ),
    ]
