# Generated by Django 3.1 on 2021-03-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delo', '0005_auto_20210312_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zadacha',
            options={'ordering': ['-data_vipolnenija'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='zadacha',
            name='fromuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
