# Generated by Django 3.1 on 2021-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0006_auto_20210312_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateTimeField(default='2021-03-13', verbose_name='Дата задачи'),
        ),
    ]
