# Generated by Django 3.1 on 2021-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0008_auto_20210314_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата задачи'),
        ),
    ]
