# Generated by Django 3.1 on 2021-03-14 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delo', '0009_auto_20210314_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='fromuser',
            field=models.ForeignKey(help_text='Заказчик', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='is_vipolneno',
            field=models.BooleanField(default=False, verbose_name='Задача выполнена'),
        ),
    ]
