# Generated by Django 3.1 on 2021-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0011_auto_20210314_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата выполнения задачи'),
        ),
    ]
