# Generated by Django 3.1 on 2021-03-14 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delo', '0012_auto_20210314_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadacha',
            name='ispolnitel',
            field=models.ForeignKey(help_text='Исполнитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ispolnitels', to=settings.AUTH_USER_MODEL),
        ),
    ]
