# Generated by Django 3.1 on 2021-03-14 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0013_zadacha_ispolnitel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_postanovki',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата задачи'),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения задачи'),
        ),
    ]
