# Generated by Django 3.1 on 2021-03-14 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0014_auto_20210314_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 25, 17, 421363), verbose_name='Дата выполнения задачи'),
        ),
    ]
