# Generated by Django 3.1 on 2021-03-15 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0015_auto_20210314_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 23, 45, 57, 649441), verbose_name='Дата выполнения задачи'),
        ),
    ]
