# Generated by Django 3.1 on 2021-03-19 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delo', '0016_auto_20210315_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='data_vipolnenija',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 11, 15, 50, 980982), verbose_name='Дата выполнения задачи'),
        ),
    ]
