# Generated by Django 3.1 on 2021-03-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0002_komunikacii_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default='Продаю дом', max_length=54, verbose_name='Статус')),
                ('krai', models.CharField(default='Краснодарский край,', max_length=54, verbose_name='Край, область')),
                ('gorod', models.CharField(default='Павловская,', max_length=54, verbose_name='Населенный пункт')),
                ('raion', models.CharField(default='Павловский район,', max_length=54, verbose_name='Район')),
                ('mikroraion', models.CharField(default='нет', max_length=54, verbose_name='Микрорайон')),
                ('ulica', models.CharField(default='Не указано,', max_length=54, verbose_name='Улица')),
                ('nomer_doma', models.CharField(default='0', max_length=5, verbose_name='Номер дома')),
                ('nomer_podezda', models.CharField(default='нет', max_length=4, verbose_name='Номер подъезда')),
                ('nomer_kvartiri', models.CharField(default='нет,', max_length=4, verbose_name='Номер квартиры')),
                ('is_activ', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=86, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
