# Generated by Django 3.1 on 2021-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0003_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='slug',
            field=models.SlugField(max_length=86, null=True, verbose_name='Ссылка'),
        ),
    ]
