# Generated by Django 3.1 on 2021-03-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0005_auto_20210308_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='slug',
            field=models.SlugField(blank=True, max_length=86, null=True, verbose_name='Ссылка'),
        ),
    ]
