# Generated by Django 3.1 on 2021-03-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articul', '0002_auto_20210308_0804'),
        ('dom', '0006_auto_20210308_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articul.articul'),
        ),
    ]
