# Generated by Django 3.1 on 2021-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0007_adres_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='date_pub',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
