# Generated by Django 3.1 on 2021-03-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articul', '0004_articul_data_vidan'),
        ('dom', '0008_adres_date_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komunikacii',
            options={'verbose_name': 'Комуникация', 'verbose_name_plural': 'Коммуникации'},
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articul.articul'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='kanalizacii',
            field=models.CharField(default='Пластик,', max_length=54, verbose_name='Канализация'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='otoplenie',
            field=models.CharField(default='Радиаторы,', max_length=54, verbose_name='Отопление'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='vodoprovod',
            field=models.CharField(default='Пластиковый', max_length=54, verbose_name='Водопровод'),
        ),
    ]
