# Generated by Django 3.1 on 2021-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0009_auto_20210309_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='komunikacii',
            name='data_kanalizacii',
            field=models.DateField(blank=True, null=True, verbose_name='Канализация дата установки'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='data_otoplenie',
            field=models.DateField(blank=True, null=True, verbose_name='Отопление дата установки'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='data_voda',
            field=models.DateField(blank=True, null=True, verbose_name='Водопровод дата установки'),
        ),
        migrations.AddField(
            model_name='komunikacii',
            name='descreption',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Заметки'),
        ),
    ]
