# Generated by Django 3.1 on 2021-03-11 14:45

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('articul', '0006_auto_20210311_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonespravka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(default='Введите название населенного пункта', max_length=54, verbose_name='Населенный пункт')),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articul.articul')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
        ),
    ]
