# Generated by Django 3.1 on 2021-03-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spravka', '0002_auto_20210311_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonespravka',
            name='slug',
        ),
    ]
