# Generated by Django 3.1 on 2021-03-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravka', '0003_remove_phonespravka_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uslug', models.CharField(default='Введите название и вид услуг', max_length=128, verbose_name='Название')),
                ('phone1', models.CharField(default='Введите номер телефона', max_length=128, verbose_name='Телефон')),
                ('phone_video', models.CharField(default='Введите номер телефона для видеосвязи', max_length=128, verbose_name='Видеосвязь')),
                ('app_video', models.CharField(default='whatsapp', max_length=128, verbose_name='Приложение для видео связи')),
                ('descrip', models.TextField(default='Заметок еще нет', max_length=2000, verbose_name='Заметки')),
            ],
        ),
        migrations.AddField(
            model_name='phonespravka',
            name='kontakti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spravka.kontakt'),
        ),
    ]
