# Generated by Django 3.1 on 2021-03-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravka', '0004_auto_20210311_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='kontakt',
            name='name_firm',
            field=models.CharField(default='Бренд', max_length=128, verbose_name='Название фирмы'),
        ),
    ]
