# Generated by Django 3.1 on 2021-03-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0010_auto_20210309_1437'),
        ('spravka', '0005_auto_20210312_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonespravka',
            name='adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.adres'),
        ),
    ]
